config/routes.rb
Rails.application.routes.draw do
  resources :cards

  root 'static_pages#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :original_text, presence: true
  validates :translated_text, presence: true
  validates :review_date, presence: true
  validate :check_texts

  before_validation :set_review_date, on: :create

  def check_texts
    if original_text.mb_chars.downcase.strip == translated_text.mb_chars.downcase.strip
      errors.add(:original_text, "similar_of_texts")
      errors.add(:translated_text, "similar_of_texts")
    end
  end

  def set_review_date
    self.review_date = 3.days.since
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to cards_path
    else
      render :new
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to cards_path
    else
      render :edit
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>
 
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :original_text %><br>
    <%= f.text_field :original_text %>
  </p>
 
  <p>
    <%= f.label :translated_text %><br>
    <%= f.text_field :translated_text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cards/edit.html.erb
<%= render "form" %> 
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<table>
	<tbody>
		<% @cards.each do |card| %>
			<tr>
				<td><%= card.id %></td>
				<td><%= card.original_text %></td>
				<td><%= card.translated_text %></td>
				<td><%= card.review_date %></td>
				<td>
					<%= link_to("Редактировать", edit_card_path(card))%>
					<%= link_to("Удалить", card_path(card), method: :delete)%>
					
				</td>	
			</tr>
		<% end %>
	</tbody>
</table>

app/views/cards/new.html.erb
<%= render "form" %>
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<section id="container">

    <header class="clearfix">
      <h1>Флэшкарточкер</h1>
      <ul class="navigation-links">
        <li><%= link_to "Все карточки", cards_path %></li>
        <li><%= link_to "Добавить карточку", new_card_path %></li>
      </ul>
    </header>

    <section>
    	<%= yield %>
    </section>

  </section>

</body>
</html>

app/views/static_pages/index.html.erb
<p style="font-size: 22px;">
	Первый в мире удобный менеджер флеш-карточек. Именно так.
</p>